GET http://localhost:5000/disposisi

###
GET http://localhost:5000/agendas

###
GET http://localhost:5000/count/disposisi

###
POST http://localhost:5000/disposisi
Content-Type: application/json

{
    "jabatan":"itunya dan anunya"
}

###
POST http://localhost:5000/signup
Content-Type: application/json

{  
    "username": "mod",  
    "email": "mod@bekcoder.com",  
    "password": "12345678",  
    "roles": ["moderator", "user"]  
}
###
POST http://localhost:5000/disposisi
Content-Type: application/json

{
    "jabatan":"istulah"
}

###
POST http://localhost:5000/agendas
Content-Type: application/json

{
  "tanggal": "2024-07-18",
  "time": "09:00:00",
  "agenda": "Meeting with client",
  "UPS": "UPS123",
  "loc": "Jakarta",
  "status": "Rapat Mendatang",
  "disposisiIds": [1, 2]
}


###
PATCH http://localhost:5000/disposisi/4
{
  "jabatan": " jadi beda"
}


###
PATCH http://localhost:5000/agendas/8
Content-Type: application/json

{
  "tanggal": "2024-07-18",
  "time": "09:00:00",
  "agenda": "Meeting with client",
  "UPS": "UPS123",
  "loc": "Jakarta",
  "status": "Rapat Mendatang",
  "disposisiIds": [1,2]
}

###
DELETE http://localhost:5000/agendas/2